workdir:
  /path/to/workdir/output
container:
  docker://naotokubota/shiba
gtf:
  /path/to/workdir/annotation.gtf
experiment_table:
  /path/to/workdir/Shiba_experiment.tsv

# PSI calculation
only_psi:
  False
fdr:
  0.05
delta_psi:
  0.1
reference_group:
  Cluster-1
alternative_group:
  Cluster-2
minimum_reads:
  10
excel:
  False
