name: Build and Push Docker Image

on:
  workflow_run:
    workflows: ["Create Release"]
    types:
      - completed
    branches:
      - github-actions-test

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract version tag
        id: extract_tag
        run: echo ::set-output name=TAG::${{ github.event.workflow_run.outputs.NEW_TAG }}

      - name: Debug TAG
        run: echo "The tag is ${{ steps.extract_tag.outputs.TAG }}"

      - name: Build and push Docker image with tag
        run: |
          docker build -t naotokubota/shiba:${{ steps.extract_tag.outputs.TAG }} -t naotokubota/shiba:latest -f docker/Dockerfile .
          docker push naotokubota/shiba:${{ steps.extract_tag.outputs.TAG }}
          docker push naotokubota/shiba:latest
