name: Update Version

on:
  push:
    paths:
      - 'VERSION'

jobs:
  update-readme-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read version from VERSION file
        id: read_version
        run: |
          NEW_VERSION=$(cat VERSION)
          echo "New version is $NEW_VERSION"
          echo "::set-output name=NEW_VERSION::$NEW_VERSION"

      - name: Get the branch name
        id: get_branch
        run: |
          BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
          echo "::set-output name=BRANCH_NAME::$BRANCH_NAME"

      - name: Update README.md with new version
        run: |
          NEW_VERSION=${{ steps.read_version.outputs.NEW_VERSION }}
          sed -i "s/# Shiba (v[0-9]*\.[0-9]*\.[0-9]*)/# Shiba (${NEW_VERSION})/" README.md

      - name: Update Shiba with new version
        run: |
          NEW_VERSION=${{ steps.read_version.outputs.NEW_VERSION }}
          sed -i "s/VERSION=\"v[0-9]*\.[0-9]*\.[0-9]*\"/VERSION=\"${NEW_VERSION}\"/" Shiba

      - name: Update scShiba with new version
        run: |
          NEW_VERSION=${{ steps.read_version.outputs.NEW_VERSION }}
          sed -i "s/VERSION=\"v[0-9]*\.[0-9]*\.[0-9]*\"/VERSION=\"${NEW_VERSION}\"/" scShiba

      - name: Update SnakeShiba with new version
        run: |
          NEW_VERSION=${{ steps.read_version.outputs.NEW_VERSION }}
          sed -i "s/VERSION = \"v[0-9]*\.[0-9]*\.[0-9]*\"/VERSION = \"${NEW_VERSION}\"/" SnakeShiba

      - name: Update SnakeScShiba with new version
        run: |
          NEW_VERSION=${{ steps.read_version.outputs.NEW_VERSION }}
          sed -i "s/VERSION = \"v[0-9]*\.[0-9]*\.[0-9]*\"/VERSION = \"${NEW_VERSION}\"/" SnakeScShiba

      - name: Update Dockerfile with new version
        run: |
          NEW_VERSION=${{ steps.read_version.outputs.NEW_VERSION }}
          sed -i "s/v[0-9]*\.[0-9]*\.[0-9]*/${NEW_VERSION}/" docker/Dockerfile

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md Shiba scShiba docker/Dockerfile
          git commit -m "actions: Ready for ${{ steps.read_version.outputs.NEW_VERSION }}"
          git push origin HEAD:${{ steps.get_branch.outputs.BRANCH_NAME }}